version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=nomado_houses
      - DB_USER=nomado
      - DB_PASSWORD=nomado123
      - DB_SSL_MODE=disable
      - JWT_SECRET=your-jwt-secret-key-here
      - PORT=8080
    volumes:
      # Mount environment file (create .env from .env.example)
      - ./backend/.env:/app/.env:ro
    networks:
      - nomado-network
    restart: unless-stopped

networks:
  nomado-network:
    driver: bridge
